version: '2'

services:




  gitserver:
    build: gitserver
    container_name: gitserver
    restart: always
    volumes:
      - repos:/home/git
      
  gitweb:
    build: gitweb
    container_name: gitweb
    restart: always
    volumes:
      - repos:/var/lib/git


# disabled: fedora package manager errors
#
  terminal_fedora:
    build: terminal_fedora
    container_name: terminal_fedora
    restart: always
    ports:
      - "2233:22"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - user_home:/home/user
      - .:/var/parent
#


  terminal_debian:
    build: terminal_debian
    container_name: terminal_debian
    restart: always
    ports:
      - "2234:22"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - user_home:/home/user
      - .:/var/parent



  jenkins:
    image: jenkins:latest
    restart: always
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home

  jsdebian:
    build: jsdebian
    container_name: jsdebian
    restart: always

# disabled: fedora package manager errors
#
  jsfedora:
    build: jsfedora
    container_name: jsfedora
    restart: always
#


  redmine:
    image: redmine
    container_name: redmine
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    depends_on:
      - db
    restart: always
    volumes:
      - redmine_files:/usr/src/redmine/files
      - repos:/var/git
      
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    restart: always
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    links:
      - db
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: example



volumes:
  jenkins_home:
  repos:
  user_home:
  db:
  redmine_files:

