version : '2'

services:

  terminal:
    build: terminal
    container_name: terminal
    restart: always
    ports:
      - "2255:22"
    volumes:
      - user_home: /home/user

volumes:
  user_home:


