version: '2'

services:

  jenkins:
    image: jenkins:latest
    restart: always
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home

  jsdebian:
    build: jsdebian
    container_name: jsdebian
    restart: always

  jsfedora:
    build: jsfedora
    container_name: jsfedora
    restart: always

  gitserver:
    build: gitserver
    container_name: gitserver
    restart: always
    volumes:
      - jenkins_repos:/home/git

  shell:
    build: shell
    container_name: shell
    restart: always
    ports:
      - "2233:22"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - jenkins_user_home:/home/user

volumes:
  jenkins_home:
  jenkins_repos:
  jenkins_user_home:

