version: '2'

services:

  jenkins:
    image: jenkins:latest
    restart: always
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home

  jsdebian:
    build: jsdebian
    container_name: jsdebian
    restart: always

  jsfedora:
    build: jsfedora
    container_name: jsfedora
    restart: always

  gitserver:
    build: gitserver
    container_name: gitserver
    restart: always

volumes:
  jenkins_home:


