version: '2'

services:
  jenkins:
    image: jenkins:latest
    restart: always
    container_name: jenkins_jenkins
    ports:
      - 8082:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home

